# Generated by Django 4.2.16 on 2024-10-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcrm', '0003_remove_agent_user_agent_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent',
        ),
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webcrm.agent'),
        ),
    ]
