# Generated by Django 4.2.16 on 2024-10-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrm', '0005_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending')], max_length=10),
        ),
    ]
