# Generated by Django 4.2.16 on 2024-11-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrm', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], max_length=10),
        ),
    ]
