# Generated by Django 4.2.16 on 2024-11-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrm', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending')], max_length=10),
        ),
    ]
